apiVersion: csi.ebs.aws.com/v1alpha1
kind: EBSCSIDriver
metadata:
  name: cluster
  namespace: openshift-aws-ebs-csi-driver-operator
  annotations:
    release.openshift.io/create-only: "true"
spec:
  managementState: Managed
