---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    containerImage: quay.io/bertinatto/aws-ebs-csi-driver-operator:v0.0.1
    categories: "Storage"
    capabilities: Basic Install
    description: |-
      Operator to install and maintain the AWS EBS CSI Driver on a cluster.
    certified: "false"
    support: https://github.com/openshift/aws-ebs-csi-driver-operator
    repository: https://github.com/openshift/aws-ebs-csi-driver-operator
    createdAt: 2020-03-24:13:08:00

    apiVersion: csi.ebs.aws.com/v1alpha1
    kind: EBSCSIDriver
    metadata:
      name: cluster
      spec:
        managementState: Managed

    alm-examples: |-
      [
        {
          "apiVersion": "csi.ebs.aws.com/v1alpha1",
          "kind": EBSCSIDriver",
          "metadata": {
            "name": "cluster"
          },
          "spec": {
            managementState": "Managed"
          }
        }
      ]
  name: aws-ebs-csi-driver-operator.v0.0.1
  namespace: aws-ebs-csi-driver-operator
spec:
  apiservicedefinitions: {}
  maturity: alpha
  version: 0.0.1
  minKubeVersion: 1.17.0
  description: |-
     Operator to install and maintain the AWS EBS CSI Driver on a cluster.
  displayName: Ember CSI Operator
  keywords: ['Ember-CSI', 'CSI']
  maintainers:
  - name: Red Hat
    email: aos-storage-staff@redhat.com
  provider:
    name: Red Hat
  labels:
    alm-owner-metering: aws-ebs-csi-driver-operator
    alm-status-descriptors: aws-ebs-csi-driver-operator.v0.0.1
  selector:
    matchLabels:
      alm-owner-metering: aws-ebs-csi-driver-operator
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: true
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: ember-csi-operator
        rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - ember-csi.io
          resources:
          - '*'
          verbs:
          - '*'

      clusterPermissions:
      - serviceAccountName: aws-ebs-csi-driver-operator
        rules:
        - apiGroups:
          - "security.openshift.io"
          resources:
          - securitycontextconstraints
          verbs:
          - use
          resourceNames:
          - privileged
          - hostmount-anyuid
        - apiGroups:
          - ember-csi.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrole
          - clusterrolebindings
          - role
          - rolebindings
          - serviceaccounts
          verbs:
          - get
          - create
          - delete
          - patch
          - update
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - list
          - create
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - create
          - delete
          - list
          - get
          - watch
          - update
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - volumeattachments
          verbs:
          - get
          - list
          - watch
          - update
          - delete
          - create
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          - csinodes
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - "*"
          resources:
          - events
          verbs:
          - create
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotclasses
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotcontents
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - csi.storage.k8s.io
          resources:
          - csidrivers
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
      deployments:
      - name: ember-csi-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ember-csi-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ember-csi-operator
            spec:
              containers:
              - command:
                - ember-csi-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ember-csi-operator
                image: docker.io/embercsi/ember-csi-operator:latest
                imagePullPolicy: Always
                name: ember-csi-operator
                ports:
                - containerPort: 60000
                  name: metrics
                readinessProbe:
                  exec:
                    command:
                    - stat
                    - /tmp/operator-sdk-ready
                  failureThreshold: 1
                  initialDelaySeconds: 4
                  periodSeconds: 10
                resources: {}
              serviceAccountName: ember-csi-operator

  customresourcedefinitions:
    owned:
    - kind: EmberCSI
      name: embercsis.ember-csi.io
      version: v1alpha1
      displayName: Deployments
      description: Represents a deployment of EmberCSI driver
      resources:
      - kind: StorageClass
        name: ''
        version: v1
      - kind: StatefulSet
        name: ''
        version: v1
      - kind: EmberCSI
        name: ''
        version: v1alpha
      - kind: Daemonset
        name: ''
        version: v1
      statusDescriptors:
        - description: The installed Ember CSI version
          displayName: Version
          path: version
      specDescriptors:
        - description: Define which Nodes the Pods are scheduled on.
          displayName: nodeSelect
          path: nodeSelector
        - description: Ember CSI driver container image to use
          displayName: image
          path: image
        - description: Config for Ember
          displayName: config
          path: config
        - description: Tolerations
          displayName: tolerations
          path: tolerations
        - description: Topologies
          displayName: topologies
          path: topologies
        - description: The type of storage backend
          displayName: X_CSI_BACKEND_CONFIG.driver
          path: config.envVars.X_CSI_BACKEND_CONFIG.driver
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:GeneralSettings'
            - 'urn:alm:descriptor:com.tectonic.ui:select:RBD'
            - 'urn:alm:descriptor:com.tectonic.ui:select:LVM'
        - description: Storage for persistence config
          displayName: X_CSI_PERSISTENCE_CONFIG.storage
          path: config.envVars.X_CSI_PERSISTENCE_CONFIG.storage
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:cephSettings'
            - 'urn:alm:descriptor:com.tectonic.ui:text'
            - 'urn:alm:descriptor:com.tectonic.ui:advanced'
        - description: The unique name of the plugin
          displayName: X_CSI_EMBER_CONFIG.plugin_name
          path: config.envVars.X_CSI_EMBER_CONFIG.plugin_name
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:cephSettings'
            - 'urn:alm:descriptor:com.tectonic.ui:text'
            - 'urn:alm:descriptor:com.tectonic.ui:advanced'
        - description: Backend name
          displayName: X_CSI_BACKEND_CONFIG.name
          path: config.envVars.X_CSI_BACKEND_CONFIG.name
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:cephSettings'
            - 'urn:alm:descriptor:com.tectonic.ui:text'
            - 'urn:alm:descriptor:com.tectonic.ui:advanced'
        - description: RBD username
          displayName: X_CSI_BACKEND_CONFIG.rbd_user
          path: config.envVars.X_CSI_BACKEND_CONFIG.rbd_user
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:cephSettings'
            - 'urn:alm:descriptor:com.tectonic.ui:text'
            - 'urn:alm:descriptor:com.tectonic.ui:advanced'
        - description: RBD Pool
          displayName: X_CSI_BACKEND_CONFIG.rbd_pool
          path: config.envVars.X_CSI_BACKEND_CONFIG.rbd_pool
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:cephSettings'
            - 'urn:alm:descriptor:com.tectonic.ui:text'
            - 'urn:alm:descriptor:com.tectonic.ui:advanced'
        - description: RBD Ceph config filename
          displayName: X_CSI_BACKEND_CONFIG.rbd_ceph_conf
          path: config.envVars.X_CSI_BACKEND_CONFIG.rbd_ceph_conf
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:cephSettings'
            - 'urn:alm:descriptor:com.tectonic.ui:text'
            - 'urn:alm:descriptor:com.tectonic.ui:advanced'
        - description: RBD Ceph keyring filename
          displayName: X_CSI_BACKEND_CONFIG.rbd_keyring_conf
          path: config.envVars.X_CSI_BACKEND_CONFIG.rbd_keyring_conf
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:cephSettings'
            - 'urn:alm:descriptor:com.tectonic.ui:text'
            - 'urn:alm:descriptor:com.tectonic.ui:advanced'
        - description: sysFiles secrets
          displayName: sysFiles secrets
          path: config.sysFiles.key
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:cephSettings'
            - 'urn:alm:descriptor:io.kubernetes:Secret'
            - 'urn:alm:descriptor:com.tectonic.ui:advanced'
        - description: sysFiles secrets
          displayName: sysFiles secrets name
          path: config.sysFiles.name
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:cephSettings'
            - 'urn:alm:descriptor:com.tectonic.ui:text'
            - 'urn:alm:descriptor:com.tectonic.ui:advanced'
